from dotenv import load_dotenv
import os
from google import genai
from rich.console import Console
from prompts import generate_coding_coach_prompt
from datetime import datetime

console = Console()

# --------------------------
# 1️⃣ Output saving setup
# --------------------------
OUTPUTS_DIR = "outputs"
os.makedirs(OUTPUTS_DIR, exist_ok=True)

def save_output(user_prompt: str, model_response: str):
    """
    Saves the model's response to a timestamped file in outputs folder.
    
    Args:
        user_prompt (str): The prompt given by the user.
        model_response (str): The response generated by the Coding Coach.
    """
    # Generate a safe timestamped filename
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    filename = f"{OUTPUTS_DIR}/{timestamp}_response.txt"
    
    # Compose the content: store prompt + response
    content = f"--- User Prompt ---\n{user_prompt}\n\n--- Coach Response ---\n{model_response}\n"
    
    # Write to file
    with open(filename, "w", encoding="utf-8") as f:
        f.write(content)
    
    console.print(f"[bold blue][Saved output to {filename}][/bold blue]")

# --------------------------
# 2️⃣ Load API key and init client
# --------------------------
load_dotenv()
API_KEY = os.getenv("GOOGLE_API_KEY")
if not API_KEY:
    raise Exception("Set GOOGLE_API_KEY in your .env file")

client = genai.Client(api_key=API_KEY)

# --------------------------
# 3️⃣ Main function to ask coach
# --------------------------
def ask_coding_coach(task_description: str) -> str:
    """Send task to coding coach LLM and return structured guidance"""
    prompt = generate_coding_coach_prompt(task_description)
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )
    return response.text

# --------------------------
# 4️⃣ Main interactive loop
# --------------------------
if __name__ == "__main__":
    console.print("[bold green]Welcome to your Coding Coach![/bold green]")
    
    while True:
        task = input("\nDescribe the coding task you want guidance on (or type 'exit' to quit):\n")
        if task.lower() in ["exit", "quit"]:
            console.print("[bold yellow]Goodbye![/bold yellow]")
            break
        
        guidance = ask_coding_coach(task)
        console.print("\n[bold magenta]Coding Coach Response:[/bold magenta]")
        console.print(guidance)
        
        # Save automatically
        save_output(task, guidance)